[build]
  publish = "."

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "/pdf-fill.mjs"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "/vendor/*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
